// <auto-generated />
namespace Twitter.Crawler.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dateTimeModification : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dateTimeModification));
        
        string IMigrationMetadata.Id
        {
            get { return "201709292130554_dateTimeModification"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
