// <auto-generated />
namespace Twitter.Crawler.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialTranlated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialTranlated));
        
        string IMigrationMetadata.Id
        {
            get { return "201709292112231_initialTranlated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
